---
abstract: "Simple way to handle Facebook's Graph API."
author:
  - 'Oklahomer <hagiwara dot go at gmail dot com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Facebook-OpenGraph
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::Recursive::Encode: 0
  Furl: 0
  HTTP::Message: 0
  JSON: 0
  MIME::Base64::URLSafe: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/oklahomer/p5-Facebook-OpenGraph.git
version: 0.04
